CREATE TABLE IF NOT EXISTS `wp_redbag` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`token`  varchar(50) NULL  COMMENT 'token',
`uid`  int(10) NULL  COMMENT 'uid',
`mch_id`  varchar(32) NULL  COMMENT '商户号',
`sub_mch_id`  varchar(32) NULL  COMMENT '子商户号',
`wxappid`  varchar(32) NULL  COMMENT '公众账号appid',
`nick_name`  varchar(32) NULL  COMMENT '提供方名称',
`send_name`  varchar(32) NULL  COMMENT '商户名称',
`total_amount`  int(10) NULL  DEFAULT 1000 COMMENT '付款金额',
`min_value`  int(10) NULL  DEFAULT 1000 COMMENT '最小红包金额',
`max_value`  int(10) NULL  DEFAULT 1000 COMMENT '最大红包金额',
`total_num`  int(10) NULL  DEFAULT 1 COMMENT '红包发放总人数',
`wishing`  varchar(255) NULL  COMMENT '红包祝福语',
`act_name`  varchar(255) NULL  COMMENT '活动名称',
`remark`  varchar(255) NULL  COMMENT '备注',
`logo_imgurl`  int(10) UNSIGNED NULL  COMMENT '商户logo的url',
`share_content`  varchar(255) NULL  COMMENT '分享文案',
`share_url`  varchar(255) NULL  COMMENT '分享链接',
`share_imgurl`  int(10) UNSIGNED NULL  COMMENT '分享的图片',
`collect_count`  int(10) NULL  DEFAULT 0 COMMENT '领取人数',
`collect_amount`  int(10) NULL  DEFAULT 0 COMMENT '已领取金额',
`collect_limit`  tinyint(2) NULL  DEFAULT 0 COMMENT '每人最多领取次数',
`partner_key`  varchar(50) NULL  COMMENT '商户API密钥',
`template`  varchar(255) NULL  DEFAULT 'default' COMMENT '素材模板',
`act_remark`  varchar(255) NULL  COMMENT '活动备注',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('redbag','微信红包','0','','1','["mch_id","wxappid","nick_name","send_name","total_amount","min_value","max_value","total_num","wishing","act_name","remark","collect_limit","partner_key","token","uid","template"]','1:基础','','','','','act_name:活动名称\r\nsend_name:商户名称\r\ntotal_amount:付款金额\r\nmin_value:最小红包\r\nmax_value:最大红包\r\ntotal_num:发放人数\r\nids:操作:[EDIT]|编辑,[DELETE]|删除,preview?id=[id]&target=_blank|预览','20','act_name:活动名称','','1427701701','1437451797','1','MyISAM','RedBag');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(50) NULL','string','','','1','','0','redbag','0','1','1430999098','1430999079','','3','','regex','get_token','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('uid','uid','int(10) NULL','num','','','1','','0','redbag','0','1','1430999121','1430999121','','3','','regex','get_mid','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('mch_id','商户号','varchar(32) NULL','string','','微信支付分配的商户号','1','','0','redbag','1','1','1427702346','1427702346','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sub_mch_id','子商户号','varchar(32) NULL','string','','可为空，微信支付分配的子商户号，受理模式下必填','0','','0','redbag','0','1','1427785321','1427702397','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wxappid','公众账号appid','varchar(32) NULL','string','','商户appid','1','','0','redbag','1','1','1427702433','1427702433','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('nick_name','提供方名称','varchar(32) NULL','string','','','1','','0','redbag','1','1','1427702473','1427702473','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('send_name','商户名称','varchar(32) NULL','string','','红包发送者名称','1','','0','redbag','1','1','1427702505','1427702505','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('total_amount','付款金额','int(10) NULL','num','1000','付款金额，单位分','1','','0','redbag','1','1','1427702603','1427702603','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('min_value','最小红包金额','int(10) NULL','num','1000','最小红包金额，单位分','1','','0','redbag','1','1','1427702653','1427702653','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('max_value','最大红包金额','int(10) NULL','num','1000','最大红包金额，单位分','1','','0','redbag','1','1','1427702703','1427702703','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('total_num','红包发放总人数','int(10) NULL','num','1','','1','','0','redbag','1','1','1427702757','1427702757','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wishing','红包祝福语','varchar(255) NULL','string','','如：感谢您参加猜灯谜活动，祝您元宵节快乐！','1','','0','redbag','1','1','1427702843','1427702843','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('act_name','活动名称','varchar(255) NULL','string','','如：猜灯谜抢红包活动','1','','0','redbag','1','1','1427702920','1427702920','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('remark','备注','varchar(255) NULL','string','','如：猜越多得越多，快来抢！','1','','0','redbag','1','1','1427703037','1427703011','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('logo_imgurl','商户logo的url','int(10) UNSIGNED NULL','picture','','','0','','0','redbag','0','1','1427785307','1427703083','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('share_content','分享文案','varchar(255) NULL','string','','如：快来参加猜灯谜活动','0','','0','redbag','0','1','1427785298','1427703125','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('share_url','分享链接','varchar(255) NULL','string','','','0','','0','redbag','0','1','1427785292','1427703167','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('share_imgurl','分享的图片','int(10) UNSIGNED NULL','picture','','','0','','0','redbag','0','1','1427785285','1427703301','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('collect_count','领取人数','int(10) NULL','num','0','','0','','0','redbag','0','1','1427785218','1427785211','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('collect_amount','已领取金额','int(10) NULL','num','0','单位为分','0','','0','redbag','0','1','1427785274','1427785262','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('collect_limit','每人最多领取次数','tinyint(2) NULL','num','0','0 表示不限制','1','','0','redbag','0','1','1427786937','1427786937','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('partner_key','商户API密钥','varchar(50) NULL','string','','用户生成支付签名','1','','0','redbag','0','1','1427850414','1427850414','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('template','素材模板','varchar(255) NULL','string','default','','1','','0','redbag','0','1','1430132068','1430132068','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('act_remark','活动备注','varchar(255) NULL','string','','','1','','0','redbag','0','1','1440488802','1440488802','','3','','regex','','3','function');
UPDATE `wp_attribute` a, wp_model m SET a.model_id = m.id WHERE a.model_name=m.`name`;


CREATE TABLE IF NOT EXISTS `wp_redbag_follow` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`redbag_id`  int(10) NULL  COMMENT '红包ID',
`follow_id`  int(10) NULL  COMMENT '粉丝ID',
`amount`  int(10) NULL  DEFAULT 0 COMMENT '领取金额',
`cTime`  int(10) NULL  COMMENT '领取时间',
`status`  char(10) NULL  DEFAULT 'SENDING' COMMENT '发放状态',
`reason`  varchar(50) NULL  COMMENT '失败原因 ',
`Rcv_time`  int(10) NULL  COMMENT '领取红包的时间 ',
`Send_time`  int(10) NULL  COMMENT '红包发送时间 ',
`Refund_time`  int(10) NULL  COMMENT '红包退款时间',
`extra`  text NULL  COMMENT '微信返回的数据集',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('redbag_follow','领取红包的用户','0','','1','["redbag_id","follow_id","amount","cTime"]','1:基础','','','','','follow_id|get_follow_name:粉丝\r\namount:领取金额（分）\r\ncTime|time_format:领取时间','20','','','1427703365','1427703721','1','MyISAM','RedBag');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('redbag_id','红包ID','int(10) NULL','num','','','1','','0','redbag_follow','0','1','1427703408','1427703408','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('follow_id','粉丝ID','int(10) NULL','num','','','1','','0','redbag_follow','0','1','1427703457','1427703457','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('amount','领取金额','int(10) NULL','num','0','单位为分','1','','0','redbag_follow','0','1','1427703546','1427703546','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cTime','领取时间','int(10) NULL','num','','','1','','0','redbag_follow','0','1','1427703593','1427703593','','3','','regex','time','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','发放状态','char(10) NULL','radio','SENDING','','1','SENDING:发放中\r\nSENT:已发放待领取\r\nFAILED：发放失败\r\nRECEIVED:已领取\r\nREFUND:已退款 ','0','redbag_follow','0','1','1443077224','1443077224','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('reason','失败原因 ','varchar(50) NULL','string','','','0','','0','redbag_follow','0','1','1443077304','1443077304','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('Rcv_time','领取红包的时间 ','int(10) NULL','datetime','','','0','','0','redbag_follow','0','1','1443077415','1443077415','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('Send_time','红包发送时间 ','int(10) NULL','datetime','','','0','','0','redbag_follow','0','1','1443077446','1443077446','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('Refund_time','红包退款时间','int(10) NULL','datetime','','','0','','0','redbag_follow','0','1','1443077472','1443077472','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('extra','微信返回的数据集','text NULL','textarea','','','0','','0','redbag_follow','0','1','1443077530','1443077530','','3','','regex','','3','function');
UPDATE `wp_attribute` a, wp_model m SET a.model_id = m.id WHERE a.model_name=m.`name`;


