CREATE TABLE IF NOT EXISTS `wp_weiba_category` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`name`  varchar(255) NULL  COMMENT '分类名称',
`token`  varchar(100) NULL  COMMENT 'token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('weiba_category','微吧分类','0','','1','["name"]','1:基础','','','','','id:分类编号\r\nname:分类名称\r\nids:操作:[EDIT]|编辑,[DELETE]|删除','10','name:请输入分类名称搜索','','1463800207','1463801532','1','MyISAM','Weiba');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','分类名称','varchar(255) NULL','string','','','1','','0','weiba_category','1','1','1465976454','1463800258','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(100) NULL','string','','','0','','0','weiba_category','0','1','1463820483','1463820483','','3','','regex','get_token','1','function');
UPDATE `wp_attribute` a, wp_model m SET a.model_id = m.id WHERE a.model_name=m.`name`;


CREATE TABLE IF NOT EXISTS `wp_weiba` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`cid`  varchar(100) NULL  COMMENT '所属分类',
`weiba_name`  varchar(255) NULL  COMMENT '版块名称',
`uid`  int(10) NULL  COMMENT '创建者ID',
`ctime`  int(10) NULL  COMMENT '创建时间',
`logo`  int(10) UNSIGNED NULL  COMMENT '版块图标',
`intro`  text NULL  COMMENT '版块说明',
`who_can_post`  tinyint(1) NULL  DEFAULT 0 COMMENT '发帖权限',
`who_can_reply`  tinyint(1) NULL  DEFAULT 0 COMMENT '回帖权限',
`follower_count`  int(10) NULL  DEFAULT 0 COMMENT '成员数',
`thread_count`  int(10) NULL  DEFAULT 0 COMMENT '帖子数',
`admin_uid`  varchar(255) NULL  COMMENT '版主',
`recommend`  tinyint(1) NULL  DEFAULT 0 COMMENT '是否设置为推荐',
`status`  tinyint(1) NULL  DEFAULT 1 COMMENT '审核状态',
`is_del`  tinyint(1) NULL  DEFAULT 0 COMMENT '是否删除',
`notify`  text NULL  COMMENT '版块公告',
`avatar_big`  text NULL  COMMENT 'avatar_big',
`avatar_middle`  text NULL  COMMENT 'avatar_middle',
`new_count`  int(10) NULL  DEFAULT 0 COMMENT '最新帖子数',
`new_day`  date  COMMENT 'new_day',
`info`  varchar(255) NULL  COMMENT '申请附件信息',
`token`  varchar(100) NULL  COMMENT 'token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('weiba','微社区','0','','1','["weiba_name","cid","logo","who_can_post","recommend","admin_uid","intro","notify"]','1:基础','','','','','id:微吧ID\r\nweiba_name:版块名称\r\ncid:版块分类\r\nthread_count:帖子数\r\nfollower_count:成员数\r\nids:操作:[EDIT]|编辑,[DELETE]|删除','10','weiba_name:请输入版块名称搜索','','1463802099','1463821750','1','MyISAM','Weiba');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cid','所属分类','varchar(100) NULL','dynamic_select','','','1','table=weiba_category&value_field=id&title_field=name','0','weiba','0','1','1463818112','1463802336','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('weiba_name','版块名称','varchar(255) NULL','string','','','1','','0','weiba','1','1','1463802421','1463802421','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('uid','创建者ID','int(10) NULL','num','','','0','','0','weiba','0','1','1463802459','1463802459','','3','','regex','get_mid','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','创建时间','int(10) NULL','datetime','','','0','','0','weiba','0','1','1463802489','1463802489','','3','','regex','time','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('logo','版块图标','int(10) UNSIGNED NULL','picture','','','1','','0','weiba','0','1','1463802555','1463802555','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('intro','版块说明','text NULL','textarea','','','1','','0','weiba','0','1','1463818545','1463802597','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('who_can_post','发帖权限','tinyint(1) NULL','bool','0','','1','0:所有人\r\n1:仅成员\r\n2:版块管理员 \r\n3:版块圈主','0','weiba','0','1','1463818512','1463802689','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('who_can_reply','回帖权限','tinyint(1) NULL','bool','0','','0','0:所有人\r\n1:仅成员','0','weiba','0','1','1463818522','1463802745','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('follower_count','成员数','int(10) NULL','num','0','','0','','0','weiba','0','1','1463802873','1463802873','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('thread_count','帖子数','int(10) NULL','num','0','','0','','0','weiba','0','1','1463802904','1463802904','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('admin_uid','版主','varchar(255) NULL','users','','','1','','0','weiba','0','1','1464408355','1463802951','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('recommend','是否设置为推荐','tinyint(1) NULL','bool','0','','1','0:否\r\n1:是','0','weiba','0','1','1463803007','1463803007','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','审核状态','tinyint(1) NULL','bool','1','','0','0:未通过\r\n1:已通过','0','weiba','0','1','1463828775','1463803060','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_del','是否删除','tinyint(1) NULL','bool','0','','0','','0','weiba','0','1','1463803123','1463803123','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('notify','版块公告','text NULL','textarea','','','1','','0','weiba','0','1','1463818189','1463803190','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('avatar_big','avatar_big','text NULL','textarea','','','0','','0','weiba','0','1','1463803240','1463803240','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('avatar_middle','avatar_middle','text NULL','textarea','','','0','','0','weiba','0','1','1463803268','1463803268','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('new_count','最新帖子数','int(10) NULL','num','0','','0','','0','weiba','0','1','1463803307','1463803307','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('new_day','new_day','date','date','','','0','','0','weiba','0','1','1463803381','1463803381','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('info','申请附件信息','varchar(255) NULL','string','','','0','','0','weiba','0','1','1463803443','1463803443','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(100) NULL','string','','','0','','0','weiba','0','1','1463820521','1463820521','','3','','regex','get_token','3','function');
UPDATE `wp_attribute` a, wp_model m SET a.model_id = m.id WHERE a.model_name=m.`name`;


CREATE TABLE IF NOT EXISTS `wp_weiba_post` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`weiba_id`  int(10) NULL  COMMENT '所属版块',
`post_uid`  int(10) NULL  COMMENT '发表者uid',
`title`  varchar(255) NOT NULL  COMMENT '帖子标题',
`content`  text NOT  NULL  COMMENT '帖子内容',
`post_time`  int(10) NULL  COMMENT '发表时间',
`reply_count`  int(10) NULL  DEFAULT 0 COMMENT '回复数',
`read_count`  int(10) NULL  DEFAULT 0 COMMENT '浏览数',
`last_reply_uid`  varchar(50) NULL  DEFAULT 0 COMMENT '最后回复人',
`last_reply_time`  int(10) NULL  DEFAULT 0 COMMENT '最后回复时间',
`digest`  tinyint(1) NULL  DEFAULT 0 COMMENT '全局精华',
`top`  tinyint(2) NULL  DEFAULT 0 COMMENT '置顶帖',
`lock`  tinyint(1) NULL  DEFAULT 0 COMMENT '锁帖',
`recommend`  tinyint(1) NULL  DEFAULT 0 COMMENT '是否设为推荐',
`recommend_time`  int(10) NULL  DEFAULT 0 COMMENT '设为推荐的时间',
`is_del`  tinyint(2) NULL  DEFAULT 0 COMMENT '是否已删除',
`reply_all_count`  int(11) NULL  DEFAULT 0 COMMENT '全部评论数目',
`attach`  varchar(255) NULL  COMMENT 'attach',
`praise`  int(10) NULL  DEFAULT 0 COMMENT '喜欢',
`from`  tinyint(1) NULL  DEFAULT 1 COMMENT '客户端类型',
`top_time`  int(10) NULL  DEFAULT 0 COMMENT 'top_time',
`is_index`  tinyint(2) NULL  DEFAULT 0 COMMENT '是否推荐到首页',
`index_img`  int(10) UNSIGNED NULL  COMMENT 'index_img',
`is_index_time`  int(10) NULL  COMMENT 'is_index_time',
`img_ids`  varchar(255) NULL  COMMENT 'img_ids',
`tag_id`  int(10) NULL  DEFAULT 0 COMMENT '标签',
`index_order`  int(10) NULL  DEFAULT 0 COMMENT '首页帖子排序',
`is_event`  tinyint(2) NULL  DEFAULT 0 COMMENT '类型',
`globle_recommend`  tinyint(2) NULL  DEFAULT 0 COMMENT '推荐到全站',
`token`  varchar(100) NULL  COMMENT 'token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('weiba_post','微社区帖子','0','','1','["weiba_id","title","content"]','1:基础','','','','','id:帖子编号\r\ntitle:帖子标题\r\nweiba_id:所属版块\r\npost_uid:发帖人\r\nread_count:浏览数\r\nreply_count:回复数\r\npost_time|time_format:发帖时间\r\nids:操作:[EDIT]|编辑,[DELETE]|删除','10','title:请输入标题搜索','','1463803589','1464405700','1','MyISAM','Weiba');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('weiba_id','所属版块','int(10) NULL','dynamic_select','','','1','table=weiba&value_field=id&title_field=weiba_name','0','weiba_post','0','1','1463804162','1463804162','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('post_uid','发表者uid','int(10) NULL','num','','','0','','0','weiba_post','0','1','1463804187','1463804187','','3','','regex','get_mid','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','帖子标题','varchar(255) NOT NULL','string','','','1','','0','weiba_post','1','1','1464345088','1463804216','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content','帖子内容','text NOT  NULL','editor','','','1','','0','weiba_post','1','1','1463804251','1463804251','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('post_time','发表时间','int(10) NULL','datetime','','','0','','0','weiba_post','0','1','1463804276','1463804276','','3','','regex','time','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('reply_count','回复数','int(10) NULL','num','0','','0','','0','weiba_post','0','1','1463804303','1463804303','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('read_count','浏览数','int(10) NULL','num','0','','0','','0','weiba_post','0','1','1463804334','1463804334','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('last_reply_uid','最后回复人','varchar(50) NULL','string','0','','0','','0','weiba_post','0','1','1463804385','1463804375','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('last_reply_time','最后回复时间','int(10) NULL','datetime','0','','0','','0','weiba_post','0','1','1463804409','1463804409','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('digest','全局精华','tinyint(1) NULL','bool','0','','0','0:否\r\n1:是','0','weiba_post','0','1','1463804452','1463804452','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('top','置顶帖','tinyint(2) NULL','bool','0','','0','0:否\r\n1:吧内\r\n2:全局','0','weiba_post','0','1','1463804490','1463804490','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('lock','锁帖','tinyint(1) NULL','bool','0','不允许回复','0','0:否\r\n1:是','0','weiba_post','0','1','1463804536','1463804536','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('recommend','是否设为推荐','tinyint(1) NULL','bool','0','','0','0:否\r\n1:是','0','weiba_post','0','1','1463804583','1463804583','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('recommend_time','设为推荐的时间','int(10) NULL','datetime','0','','0','','0','weiba_post','0','1','1463804636','1463804636','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_del','是否已删除','tinyint(2) NULL','bool','0','','0','0:否\r\n1:是','0','weiba_post','0','1','1463804676','1463804676','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('reply_all_count','全部评论数目','int(11) NULL','num','0','','0','','0','weiba_post','0','1','1463804754','1463804754','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('attach','attach','varchar(255) NULL','file','','','0','','0','weiba_post','0','1','1463804814','1463804814','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('praise','喜欢','int(10) NULL','num','0','','0','','0','weiba_post','0','1','1463804855','1463804845','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('from','客户端类型','tinyint(1) NULL','bool','1','','0','0:网站\r\n1:手机网页版\r\n2:android\r\n3:iphone','0','weiba_post','0','1','1463804926','1463804926','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('top_time','top_time','int(10) NULL','num','0','','0','','0','weiba_post','0','1','1463804947','1463804947','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_index','是否推荐到首页','tinyint(2) NULL','bool','0','','0','0:否\r\n1:是','0','weiba_post','0','1','1463804998','1463804998','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('index_img','index_img','int(10) UNSIGNED NULL','picture','','','0','','0','weiba_post','0','1','1463805024','1463805024','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_index_time','is_index_time','int(10) NULL','num','','','0','','0','weiba_post','0','1','1463805038','1463805038','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('img_ids','img_ids','varchar(255) NULL','string','','','0','','0','weiba_post','0','1','1463805051','1463805051','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('tag_id','标签','int(10) NULL','num','0','','0','','0','weiba_post','0','1','1463805075','1463805075','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('index_order','首页帖子排序','int(10) NULL','num','0','','0','','0','weiba_post','0','1','1463805101','1463805101','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_event','类型','tinyint(2) NULL','bool','0','','0','0:话题\r\n1:活动','0','weiba_post','0','1','1463805144','1463805144','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('globle_recommend','推荐到全站','tinyint(2) NULL','bool','0','','0','0:否\r\n1:是','0','weiba_post','0','1','1463805178','1463805178','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(100) NULL','string','','','0','','0','weiba_post','0','1','1463820555','1463820555','','3','','regex','get_token','1','function');
UPDATE `wp_attribute` a, wp_model m SET a.model_id = m.id WHERE a.model_name=m.`name`;


